### ISSUE TITLE
Agenda navlink highlighted when we're on "my profile" page

### ISSUE THREAD

**Issue by AhmedNSidd** [sdevalapurkar/schedulearn#101]
![image](https://user-images.githubusercontent.com/36286128/52392699-de344680-2a57-11e9-9076-c11fc79871e7.png)

**Comment by sdevalapurkar** [comment]
Thanks for creating this 👍 @AhmedNSidd

**Comment by AhmedNSidd** [comment]
> Thanks for creating this 👍 @AhmedNSidd

no worries boss
