### ISSUE TITLE
The more options button doesn't work with a windowed browser and a mouse click

### ISSUE THREAD

**Issue by AhmedNSidd** [sdevalapurkar/schedulearn#105]
<img width="736" alt="screen shot 2019-02-08 at 1 42 43 pm" src="https://user-images.githubusercontent.com/36286128/52507809-7bea5b80-2ba7-11e9-8393-a6ec378971e4.png">

The more options button works on a mobile, but on a windowed web browser, a mouse click doesnt work. Most likely because the click handler is searching for a finger tap and not a mouse click. Needs fixing.

**Comment by Nppatel97** [comment]
PR #109 addresses this bug. The more options button now works fine.
