### ISSUE TITLE
If there are no history lessons to display, show a picture with a caption.

### ISSUE THREAD

**Issue by AhmedNSidd** [sdevalapurkar/schedulearn#112]
Similar to how in the agenda page and in the tutors/student page, there is a image with a caption telling the user that there are no lesson or no tutors/students added to display. I want something like that when there are no history lessons to display in the public_profile.html and my_profile.html. There is a todo statement in each file telling you where you should add the image + caption.

**Comment by AhmedNSidd** [comment]
First todo is in schedule_lessons/templates/dashboard/my_profile.html at line 257 
Second todo is in schedule_lessons/templates/dashboard/public_profile.html at line 272.

You can try to find a logo online. Find something in black and white that has something to do with "history" since that's where the image is gonna go. Pixabay is a pretty good place for this stuff: https://pixabay.com/vectors/search/time/?colors=grayscale. I was messing around with Sketch and I also made a svg that you can use:

<svg width="40px" height="56px" viewBox="0 0 40 56" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Artboard" transform="translate(-175.000000, -160.000000)" stroke="#979797">
            <g id="Logo" transform="translate(175.000000, 161.000000)">
                <g id="Clock" transform="translate(10.000000, 25.000000)">
                    <path d="M25,5 L25,5 C30.5228475,10.5228475 30.5228475,19.4771525 25,25 L25,25 C19.4771525,30.5228475 10.5228475,30.5228475 5,25 L5,25 C-0.522847498,19.4771525 -0.522847498,10.5228475 5,5 L5,5 C10.5228475,-0.522847498 19.4771525,-0.522847498 25,5 Z" id="Path"></path>
                    <path d="M22.383473,5.74758473 L15,15" id="Path-2"></path>
                    <path d="M15,15 L15,27.5040523" id="Path-3"></path>
                </g>
                <g id="Arrow">
                    <path d="M32.0852208,26.8653005 L32.0852208,26.8653005 C30.2600012,17.8507485 21.899194,11.6872402 12.7481426,12.6101886 L12.5425146,12.6309277 L12.5425146,22 L0.55402598,9.79642616 L12.5425146,0.254582454 L12.5425146,6.77586802 L12.5425146,6.77586802 C25.1907689,6.77586802 35.6929911,16.5416917 36.610877,29.1565964 L36.7574888,31.1715465 L32.0852208,26.8653005 Z" id="Path-5"></path>
                </g>
            </g>
        </g>
    </g>
</svg>

Lemme know if you have any questions @DSchriemer

**Comment by DSchriemer** [comment]
Closed, let me know if you would still like any changes
