### ISSUE TITLE
Change design of facebook and google login buttons  

### ISSUE THREAD

**Issue by AhmedNSidd** [sdevalapurkar/schedulearn#117]
So facebook has a problem with how our buttons look right now. 
<img width="909" alt="Screen Shot 2019-05-14 at 9 41 22 PM" src="https://user-images.githubusercontent.com/36286128/57742949-0eac0200-7691-11e9-81da-c462cb0a4c4f.png">
The problem is that the logo needs to be distinguishable. Note how the the entire button is blue. So we need to change the design of the buttons and when we do that, we'll need to change the look of the google button too, probably. One good way of fixing this would be to change the color of the button to a white, make the borders blue (for facebook) or red (for google) and then make the text and logo the respective blue or red color depending on if it's google or facebook. 

Files to be changed are: 
schedule_lessons/template/account/login.html
schedule_lessons/template/account/signup.html
schedule_lessons/accounts/static/accounts/css/login.css (probably)
schedule_lessons/accounts/static/accounts/css/signup.css (probably)

If you have any more questions on how it should look, just ask or alternatively, visit these links:

https://developers.facebook.com/policy/#login
https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign
https://en.facebookbrand.com/

**Comment by sdevalapurkar** [comment]
did facebook reach out to you regarding this @AhmedNSidd ?

**Comment by AhmedNSidd** [comment]
Yep @sdevalapurkar, they emailed me. After we fix this, I got to let them know I fixed it so the facebook login works

**Comment by DSchriemer** [comment]
Am I good to close this? @AhmedNSidd

**Comment by AhmedNSidd** [comment]
Yuppers
