### ISSUE TITLE
The name of a setting overlaps with the on/off button on mobile.

### ISSUE THREAD

**Issue by AhmedNSidd** [sdevalapurkar/schedulearn#165]
<img width="395" alt="Screen Shot 2019-09-03 at 4 27 15 PM" src="https://user-images.githubusercontent.com/36286128/64177216-b713eb00-ce67-11e9-9670-9b97d520fd13.png">

The name of a setting can overlap with the on/off button. The fix shouldn't be so hard. I reckon adding margin-right should fix this issue.

**Comment by sdevalapurkar** [comment]
I am looking into this 😄
