### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [sdevalapurkar/schedulearn#97]
Hi @sdevalapurkar , I'm a logo designer and I can make a free logo for your project. I visited the website, it looks really good. So, what do you say about a logo?

**Comment by sdevalapurkar** [comment]
hey @tebriz159 thank you for the comment, for now I think our team is satisfied with the current simplistic design. Please don't prioritize this work. If you have time, however; and could possibly post a mockup design then we would love to take a look at it
